---
name: Run Unit Tests

'on':
  - pull_request
  - push

jobs:
  testing:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v2
        name: Set up golang 1.17
        with:
          go-version: '1.17.7'
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Run Tests
        run: go test ./...
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup E2E testing environment
        run: docker-compose -f deployments/compose.yaml up -d --build
      - name: Wait for Keycloak import to complete
        run: deployments/wait_for_keycloak_import.sh deployments/compose.yaml
      - name: Install test environment
        run: npm --prefix test ci
      - name: E2E tests
        run: npm --prefix test test
